### ISSUE TITLE
Roadmap definition

### ISSUE THREAD

**Issue by lundelius** [webuildcity/wbc#2]
Hi,
we need priorities in our feature-lists... and what kind of Milestones we are aware...
- [ ] Core-App (BBS)
  - [ ] APIs to OpenDataPortals --> Which Cities next?
- [x] Hamburg
- [ ] Berlin
- Koblenz
- Salzburg
- Aarhus
  - [ ] Upload-File Feature for Admin-Panel @MagdaN 
    - [ ] 3D Model 
    - [ ] 
- [ ] Usability Improvements
